### ISSUE TITLE
OpenApi Overriden and duplicated exemples 

### ISSUE THREAD

**Issue by Apoorva64** [microcks/microcks#1037] opened 2024-01-08 14:44 UTC
### Describe the bug

When loading https://gitlab.com/api/v4/projects/53591717/repository/files/complex-example-2%2Fopenapi.yaml/raw?head=main 
The exemples are duplicated and Overriden.
![image](https://github.com/microcks/microcks/assets/60534691/4e1acd3b-a903-4d43-a9a7-8ba22d05900e)
Here we can see that the Mock response for /owner/0 and /owner/0/car are the same.

### Expected behavior

 /owner/0/car should return 
```json
  [
    { "model": "BMW X5", "year": 2018 },
    { "model": "Tesla Model 3", "year": 2020 },
  ]
```
from the exemple

```yaml
summary: Laurent's Cars
value:
  [
    { "model": "BMW X5", "year": 2018 },
    { "model": "Tesla Model 3", "year": 2020 },
  ]
```

### Actual behavior

but Returns the same exemple as /owner/0

### How to Reproduce?

1. import https://gitlab.com/api/v4/projects/53591717/repository/files/complex-example-2%2Fopenapi.yaml/raw?head=main with importer
2. go to the Service 

### Microcks version or git rev

docker.io/microcks/microcks:nightly@sha256:22eef53ce58777d07340b9a1fadccdf356f45a034034c208f8d996cb0330cfe1

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

**Comment by lbroudoux** [comment] 2024-01-08 15:27
This is a side effect of #1035. Will fix it asap.

**Comment by lbroudoux** [comment] 2024-01-08 16:36
Found that the `ReferenceResolver` had a local cache, the key is the relative path name... And because we have `get/200/examples/maxime/yaml` several times at different absolute locations, there's a mix and match 🤣

**Comment by lbroudoux** [comment] 2024-01-08 17:03
A fix has been committed and should be available shortly. I've completed the unit test to have a deep inspection of parsing results. Let me know if everything is now ok.

**Comment by Apoorva64** [comment] 2024-01-09 09:09
```
microcks                                   | 09:00:37.973  INFO 1 --- [080-exec-7] i.g.microcks.util.ReferenceResolver      : Downloading a reference file at {CORRECT_GITLAB_PATH}
microcks                                   | 09:00:37.973 DEBUG 1 --- [080-exec-7] i.g.microcks.util.HTTPDownloader         : Secret for {CORRECT_GITLAB_PATH} contains token only, assuming Authorization Bearer
microcks                                   | 09:00:38.059 ERROR 1 --- [080-exec-7] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 18] with root cause
microcks                                   | 
microcks                                   | java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 18
microcks                                   |    at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4606)
microcks                                   |    at java.base/java.lang.String.substring(String.java:2709)
```

@lbroudoux i've got an error when i try to import an OpenApi. But i can't find what it is.

**Comment by lbroudoux** [comment] 2024-01-09 09:11
Damned... All the unit tests are OK though ... Is it only for a file located on GitLab or do you encounter the same issue on other repo?

**Comment by Apoorva64** [comment] 2024-01-09 09:13
Idk exactly what it is. I am going to start a dev enviroment to see where the error is.

**Comment by lbroudoux** [comment] 2024-01-09 10:10
Can't reproduce it at the moment either on GitLab or GitHub

**Comment by Apoorva64** [comment] 2024-01-09 10:17
I found when it happens.
It happens when a ref dosen't have "/" in it.

For exemple there are two files like this
```
- baseContext/file1.yaml
- baseContext/file2.yaml
```

and in file2.yaml we have a ref like this:
$ref: "file1.yaml".

bug at line 160 in file webapp/src/main/java/io/github/microcks/util/AbstractJsonRepositoryImporter.java

**Comment by lbroudoux** [comment] 2024-01-09 10:21
Will replace it with:

```java
String referencePath = ref.contains("/") ? ref.substring(0, ref.lastIndexOf('/')) : ".";
String referenceContext = buildContext(baseContext, referencePath);
```

**Comment by Apoorva64** [comment] 2024-01-09 10:56
Importing works for my tests at Orange.

But the exemples are not shown in the documentation. Using importer with "
https://gitlab.com/api/v4/projects/53591717/repository/files/complex-example-2%2Fopenapi.yaml/raw?head=main"
![image](https://github.com/microcks/microcks/assets/60534691/d3cff01b-d158-45f9-abe6-1ebd2eff660b)

**Comment by lbroudoux** [comment] 2024-01-09 13:00
I've got the same results here. Looks like Redocly has trouble rendering examples coming from references. The referenced files are correctly fetched from the Microcks server but not rendered in the Redocly UI... Don't know how to go further on this.

**Comment by lbroudoux** [comment] 2024-01-09 13:07
@Apoorva64 Let me know if everything else seems ok to you so that I can release the `1.8.1` today

**Comment by Apoorva64** [comment] 2024-01-09 13:33
Everything else looks OK for me

**Comment by Apoorva64** [comment] 2024-01-09 13:36
@lbroudoux Github is currently dying https://www.githubstatus.com/ . You should probably wait before releasing

**Comment by lbroudoux** [comment] 2024-01-09 13:39
Oops.. good catch. Will wait before launching the release process 🤞

**Comment by Apoorva64** [comment] 2024-01-09 14:29
@lbroudoux i didn't follow the advancements in Microcks. Has externalValue been implemented?

**Comment by lbroudoux** [comment] 2024-01-09 14:35
Not at the moment. Will be for next release 😉

**Closed by lbroudoux** 2024-01-09 14:35 UTC
Labels: kind/bug, component/mocks, component/importer
