### ISSUE TITLE
Runner OPENAPI_SCHEMA: does not properly handle invalid response

### ISSUE THREAD

**Issue by nmasse-itix** [microcks/microcks#102] opened 2018-12-25 16:48 UTC
Hi !

I was trying to validate the following backend : 
http://loadapi-server-loadapi-server.app.itix.fr/

Against the following OpenAPI Schema using the OPENAPI_SCHEMA runner: 
https://github.com/nmasse-itix/Load-API/blob/master/openapi.yaml

<img width="1230" alt="screenshot 2018-12-25 at 17 43 03" src="https://user-images.githubusercontent.com/7472564/50424894-8c02e180-086c-11e9-868a-af97ff675358.png">

The backend fails to properly respond because of two slashes in the URL (one in the test endpoint, one in the Open API Schema) but Microcks fails to catch the invalid response from the server. 

<img width="1215" alt="screenshot 2018-12-25 at 17 45 44" src="https://user-images.githubusercontent.com/7472564/50424903-ec921e80-086c-11e9-91db-d95670be3976.png">

The response is clearly out of specification (404 + wrong content type), isn't it ?

**Comment by lbroudoux** [comment] 2018-12-26 17:58
Hi @nmasse-itix ,

I've succeeded reproducing this and you're right thinking it's not the intended behaviour.
Test return computed in this case is a matter of many parameters:
* When checking [OpenAPITestRunner here](https://github.com/microcks/microcks/blob/master/src/main/java/io/github/microcks/service/TestRunnerService.java#L257), it appears that `responceCode` validation it by default set to false so that runner only focus on body content,
* It appears that for now, response `Content-Type` is not analysed nor compared to expected one (which I consider is a flaw in the implementation), 
* Finally when checking is [there's content in the response](https://github.com/microcks/microcks/blob/master/src/main/java/io/github/microcks/util/openapi/OpenAPITestRunner.java#L150) but none is expected, it only check the `Content-Lenght` HTTP header that is not defined in your API implementation.

So there's at least 3 flaws explaining why this test is marked as success despite it should ba failure. Now, this is just the diagnosis, I should know find some elegant ways to make the implementation of all this checks more robust.

Thanks for the issue!

**Comment by lbroudoux** [comment] 2019-01-31 13:32
Now fixed ;-)

**Closed by lbroudoux** 2019-01-31 13:32 UTC
Labels: component/tests, kind/bug
