### ISSUE TITLE
Integrate with RedHat-SSO

### ISSUE THREAD

**Issue by zhushendhh** [microcks/microcks#160] opened 2019-08-02 02:53 UTC
Hi,

I have an issue here:

Your app provides a keyclock but we want to integrate with our RH-SSO (also a keyclock). It working via HTTPs, and after create oauthclient and configure the realm in RH-SSO, we can login the microcks portal with sso user but cannot create APIs and importers.

The browser will report below error code  HTTP:401

**Comment by zhushendhh** [comment] 2019-08-02 02:54
The microcks pod will show below logs :

[ERROR] org.keycloak.adapters.rotation.JWKPublicKeyLocator - Error when sending request to retrieve realm keys
org.keycloak.adapters.HttpClientAdapterException: IO error
	at org.keycloak.adapters.HttpAdapterUtils.sendJsonHttpRequest(HttpAdapterUtils.java:58)
	at org.keycloak.adapters.rotation.JWKPublicKeyLocator.sendRequest(JWKPublicKeyLocator.java:99)
	at org.keycloak.adapters.rotation.JWKPublicKeyLocator.getPublicKey(JWKPublicKeyLocator.java:63)
	at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.getPublicKey(AdapterRSATokenVerifier.java:44)
	at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:55)
	at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:37)
	at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticateToken(BearerTokenRequestAuthenticator.java:87)
	at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticate(BearerTokenRequestAuthenticator.java:82)
	at org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:68)
	at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.authenticateInternal(AbstractKeycloakAuthenticatorValve.java:203)
	at org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve.authenticate(KeycloakAuthenticatorValve.java:50)
	at org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve.doAuthenticate(KeycloakAuthenticatorValve.java:57)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:575)
	at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.invoke(AbstractKeycloakAuthenticatorValve.java:181)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:553)
	at org.keycloak.adapters.SniSSLSocketFactory.connectSocket(SniSSLSocketFactory.java:109)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:412)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.keycloak.adapters.HttpAdapterUtils.sendJsonHttpRequest(HttpAdapterUtils.java:37)
	... 26 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:397)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:302)
	at sun.security.validator.Validator.validate(Validator.java:262)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)
	... 46 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:392)
	... 52 common frames omitted
[ERROR] org.keycloak.adapters.rotation.AdapterRSATokenVerifier - Didn't find publicKey for kid: uxJ6vNvrD-EdkLZgPwP_TxtkmGK17Onctn9jInOdE54
[ERROR] org.keycloak.adapters.BearerTokenRequestAuthenticator - Failed to verify token
org.keycloak.common.VerificationException: Didn't find publicKey for specified kid
	at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.getPublicKey(AdapterRSATokenVerifier.java:47)
	at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:55)
	at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:37)
	at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticateToken(BearerTokenRequestAuthenticator.java:87)
	at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticate(BearerTokenRequestAuthenticator.java:82)
	at org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:68)
	at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.authenticateInternal(AbstractKeycloakAuthenticatorValve.java:203)
	at org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve.authenticate(KeycloakAuthenticatorValve.java:50)
	at org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve.doAuthenticate(KeycloakAuthenticatorValve.java:57)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:575)
	at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.invoke(AbstractKeycloakAuthenticatorValve.java:181)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] org.keycloak.adapters.rotation.AdapterRSATokenVerifier - Didn't find publicKey for kid: uxJ6vNvrD-EdkLZgPwP_TxtkmGK17Onctn9jInOdE54
[ERROR] org.keycloak.adapters.BearerTokenRequestAuthenticator - Failed to verify token
org.keycloak.common.VerificationException: Didn't find publicKey for specified kid
	at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.getPublicKey(AdapterRSATokenVerifier.java:47)
	at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:55)
	at org.keycloak.adapters.rotation.AdapterRSATokenVerifier.verifyToken(AdapterRSATokenVerifier.java:37)
	at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticateToken(BearerTokenRequestAuthenticator.java:87)
	at org.keycloak.adapters.BearerTokenRequestAuthenticator.authenticate(BearerTokenRequestAuthenticator.java:82)
	at org.keycloak.adapters.RequestAuthenticator.authenticate(RequestAuthenticator.java:68)
	at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.authenticateInternal(AbstractKeycloakAuthenticatorValve.java:203)
	at org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve.authenticate(KeycloakAuthenticatorValve.java:50)
	at org.keycloak.adapters.tomcat.KeycloakAuthenticatorValve.doAuthenticate(KeycloakAuthenticatorValve.java:57)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:575)
	at org.keycloak.adapters.tomcat.AbstractKeycloakAuthenticatorValve.invoke(AbstractKeycloakAuthenticatorValve.java:181)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zhushendhh** [comment] 2019-08-02 02:55
The strange question is : I can jump to SSO and complete the login operation, but cannot create/list jobs/api/counts . Always get HTTP401 error

**Comment by zhushendhh** [comment] 2019-08-02 02:57
BTW, I use this template :
https://github.com/microcks/microcks/blob/master/install/openshift/openshift-persistent-no-keycloak-template-https.yml

**Comment by lbroudoux** [comment] 2019-08-02 07:56
Hum ... this seems strange actually ... But I think I can remember such an error when there was a mix of both HTTP and HTTPS configured URL ...

What I will look like / check for this:
* Value of `KEYCLOAK_URL` env variable from the Microcks pod > Check it is correct and uses HTTPS
* Value of Microcks redirect URL in the RH-SSO realm definition > Check it matches with your route def and uses HTTPS,
* Value of `keycloak.disable-trust-manager=true` in `microcks-config` ConfigMap / `application.properties` key > Check it is true to allow using auto-signed certificates

**Comment by zhushendhh** [comment] 2019-08-02 08:59
Hi @lbroudoux 

Thank you for your kindly response.

I have a concern that your default keycloak pod contains a init container named:jimmidyson/pemtokeystore:v0.2.0 and RH-SSO official template doesn't include it. Is this a necessary configuration or part for the keyclock(RH-SSO)?

Below is my settings and detailes of configmap:
 -KEYCLOAK_URL: https://sso-franktest.apps.paas-test.ubrmb.com/auth/
 -TEST_CALLBACK_URL: http://microcks:8080
 -POSTMAN_RUNNER_URL: http://microcks-postman-runtime:8080
- Microcks redirect URL in the RH-SSO realm: https://sso-franktest.apps.paas-test.ubrmb.com/auth/realms/microcks/broker/openshift-v3/endpoint
================================================================
# Application configuration properties
tests-callback.url=${TEST_CALLBACK_URL}
postman-runner.url=${POSTMAN_RUNNER_URL}

network.username=
network.password=

validation.resourceUrl=https://microcks-poc.apps.paas-test.ubrmb.com/api/resources/
services.update.interval=${SERVICES_UPDATE_INTERVAL:0 0 0/2 * * *}
mocks.rest.enable-cors-policy=${ENABLE_CORS_POLICY:true}

# Logging configuration properties
logging.config=/deployments/config/logback.xml

# Keycloak configuration properties
keycloak.auth-server-url=${KEYCLOAK_URL:http://localhost:8180/auth}
keycloak.realm=microcks
keycloak.resource=microcks-app
keycloak.bearer-only=true
keycloak.ssl-required=external
keycloak.disable-trust-manager=true


keycloak.security-constraints[0].authRoles[0]=admin
keycloak.security-constraints[0].authRoles[1]=manager
keycloak.security-constraints[0].authRoles[2]=user
keycloak.security-constraints[0].securityCollections[0].name=Insecure stuffs
keycloak.security-constraints[0].securityCollections[0].patterns[0]=/api/services
keycloak.security-constraints[0].securityCollections[0].patterns[1]=/api/services/count
keycloak.security-constraints[0].securityCollections[0].patterns[2]=/api/jobs
keycloak.security-constraints[0].securityCollections[0].patterns[3]=/api/jobs/count

**Comment by lbroudoux** [comment] 2019-08-02 17:06
Yes you're right. This may be a good point ...

I use this init-container to integrate OpenShift service account certificate into the Keycloak keystore. This is mandatory for using OpenShift v3 identity provider as an identity broker in keycloak. If not using this init-container, you'll have to provide the OpenShift certificate using a secret to make it available to Keycloak.

However, I doubt this is the cause of your problem. As you said, authentication flow seems to succeed as you can login, so RH-SSO should be able to call the OCP identity provider.

Problem seems to be when keycloak adapter in Microcks is trying to validate the token ... Usually this problem comes from different Keycloak URLs used when issuing the token and when validating it later.

Will think about it...

**Comment by lbroudoux** [comment] 2019-08-02 17:12
You could also try putting the keycloak adapter on DEBUG log level on the Microcks pod. You can do this modifying the logback.xml file in ConfigMap.

**Comment by zhushendhh** [comment] 2019-08-05 01:46
Hi

I found if I add below perm again the issue is gone, so it seems to be a cert issue here.
"keycloak.disable-trust-manager=true"
Do you agree to add this comment into the default configmap?

BTW, I found another issue with the OCP template that some of the menus cannot be clicked in the console and it seems similar like below issue hope you can update the template base on this it: https://github.com/microcks/microcks/issues/120

Thank you again for your help.

**Comment by lbroudoux** [comment] 2019-08-05 08:04
Hi @zhushendhh ,

Happy to know it is now working but not sure to understand what solve your problem...
Considering your above messages, it seems that `keycloak.disable-trust-manager=true` was already there into `application.properties`. Do you mean you have to add it a second time so that it solve the cert validation issue ??

Also, could you details the issue from #120 you still encounter ? Most of the issues detailed there should now be solved and I'm surprised if you still get them...

Thanks for your time,

**Comment by zhushendhh** [comment] 2019-08-06 01:38
@lbroudoux 
Thank you for your feedback.

The reason should be the deployment didn't auto rollout at the first time, and then I manual rollout it.

The second question is we found some of the menu cannot be clicked in the admin console and the link is a similar issue from my understanding, not sure if it is merged into the code. The OCP templates were updated at about 2 months ago but the issue was fixed just a couple of days.

Below is the error when clicking the issued menu via debug mode in the browser:

admin portal --- select one api --- Statistics:Mocks invocations :
=======================================================
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'admin/invocations/HelloServiceSoapBinding%20MockService/1.0'
Error: Cannot match any routes. URL Segment: 'admin/invocations/HelloServiceSoapBinding%20MockService/1.0'
    at n.noMatchError (main.9faf9e16528f9cf98704.js:1)
    at t.selector (main.9faf9e16528f9cf98704.js:1)
    at t.error (main.9faf9e16528f9cf98704.js:1)
    at t._error (main.9faf9e16528f9cf98704.js:1)
    at t.error (main.9faf9e16528f9cf98704.js:1)
    at t._error (main.9faf9e16528f9cf98704.js:1)
    at t.error (main.9faf9e16528f9cf98704.js:1)
    at t._error (main.9faf9e16528f9cf98704.js:1)
    at t.error (main.9faf9e16528f9cf98704.js:1)
    at t._error (main.9faf9e16528f9cf98704.js:1)
    at n.noMatchError (main.9faf9e16528f9cf98704.js:1)
    at t.selector (main.9faf9e16528f9cf98704.js:1)
    at t.error (main.9faf9e16528f9cf98704.js:1)
    at t._error (main.9faf9e16528f9cf98704.js:1)
    at t.error (main.9faf9e16528f9cf98704.js:1)
    at t._error (main.9faf9e16528f9cf98704.js:1)
    at t.error (main.9faf9e16528f9cf98704.js:1)
    at t._error (main.9faf9e16528f9cf98704.js:1)
    at t.error (main.9faf9e16528f9cf98704.js:1)
    at t._error (main.9faf9e16528f9cf98704.js:1)
    at j (polyfills.9f773b75ffcda6bb2a95.js:1)
    at j (polyfills.9f773b75ffcda6bb2a95.js:1)
    at polyfills.9f773b75ffcda6bb2a95.js:1
    at e.invokeTask (polyfills.9f773b75ffcda6bb2a95.js:1)
    at Object.onInvokeTask (main.9faf9e16528f9cf98704.js:1)
    at e.invokeTask (polyfills.9f773b75ffcda6bb2a95.js:1)
    at t.runTask (polyfills.9f773b75ffcda6bb2a95.js:1)
    at d (polyfills.9f773b75ffcda6bb2a95.js:1)
    at t.invokeTask (polyfills.9f773b75ffcda6bb2a95.js:1)
    at invoke (polyfills.9f773b75ffcda6bb2a95.js:1)
et @ main.9faf9e16528f9cf98704.js:1
n.handleError @ main.9faf9e16528f9cf98704.js:1
next @ main.9faf9e16528f9cf98704.js:1
t.object.i @ main.9faf9e16528f9cf98704.js:1
t.__tryOrUnsub @ main.9faf9e16528f9cf98704.js:1
t.next @ main.9faf9e16528f9cf98704.js:1
t._next @ main.9faf9e16528f9cf98704.js:1
t.next @ main.9faf9e16528f9cf98704.js:1
t.next @ main.9faf9e16528f9cf98704.js:1
t.emit @ main.9faf9e16528f9cf98704.js:1
(anonymous) @ main.9faf9e16528f9cf98704.js:1
e.invoke @ polyfills.9f773b75ffcda6bb2a95.js:1
t.run @ polyfills.9f773b75ffcda6bb2a95.js:1
n.runOutsideAngular @ main.9faf9e16528f9cf98704.js:1
onHandleError @ main.9faf9e16528f9cf98704.js:1
e.handleError @ polyfills.9f773b75ffcda6bb2a95.js:1
t.runGuarded @ polyfills.9f773b75ffcda6bb2a95.js:1
e @ polyfills.9f773b75ffcda6bb2a95.js:1
n.microtaskDrainDone @ polyfills.9f773b75ffcda6bb2a95.js:1
d @ polyfills.9f773b75ffcda6bb2a95.js:1
t.invokeTask @ polyfills.9f773b75ffcda6bb2a95.js:1
invoke @ polyfills.9f773b75ffcda6bb2a95.js:1
n.args.(anonymous function) @ polyfills.9f773b75ffcda6bb2a95.js:1
setTimeout (async)
c @ polyfills.9f773b75ffcda6bb2a95.js:1
e.scheduleTask @ polyfills.9f773b75ffcda6bb2a95.js:1
onScheduleTask @ polyfills.9f773b75ffcda6bb2a95.js:1
e.scheduleTask @ polyfills.9f773b75ffcda6bb2a95.js:1
t.scheduleTask @ polyfills.9f773b75ffcda6bb2a95.js:1
t.scheduleMacroTask @ polyfills.9f773b75ffcda6bb2a95.js:1
h @ polyfills.9f773b75ffcda6bb2a95.js:1
(anonymous) @ polyfills.9f773b75ffcda6bb2a95.js:1
i.(anonymous function) @ polyfills.9f773b75ffcda6bb2a95.js:1
(anonymous) @ main.9faf9e16528f9cf98704.js:1
t.object.i @ main.9faf9e16528f9cf98704.js:1
t.__tryOrUnsub @ main.9faf9e16528f9cf98704.js:1
t.next @ main.9faf9e16528f9cf98704.js:1
t._next @ main.9faf9e16528f9cf98704.js:1
t.next @ main.9faf9e16528f9cf98704.js:1
t.next @ main.9faf9e16528f9cf98704.js:1
t.emit @ main.9faf9e16528f9cf98704.js:1
(anonymous) @ main.9faf9e16528f9cf98704.js:1
e.invokeTask @ polyfills.9f773b75ffcda6bb2a95.js:1
onInvokeTask @ main.9faf9e16528f9cf98704.js:1
e.invokeTask @ polyfills.9f773b75ffcda6bb2a95.js:1
t.runTask @ polyfills.9f773b75ffcda6bb2a95.js:1
t.invokeTask @ polyfills.9f773b75ffcda6bb2a95.js:1
_ @ polyfills.9f773b75ffcda6bb2a95.js:1
m @ polyfills.9f773b75ffcda6bb2a95.js:1
==============================================================


admin portal --- Preformance
==============================================================
RROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: '0'
Error: Cannot match any routes. URL Segment: '0'
    at n.noMatchError (main.9faf9e16528f9cf98704.js:1)
    at t.selector (main.9faf9e16528f9cf98704.js:1)
    at t.error (main.9faf9e16528f9cf98704.js:1)
    at t._error (main.9faf9e16528f9cf98704.js:1)
    at t.error (main.9faf9e16528f9cf98704.js:1)
    at t._error (main.9faf9e16528f9cf98704.js:1)
    at t.error (main.9faf9e16528f9cf98704.js:1)
    at t._error (main.9faf9e16528f9cf98704.js:1)
    at t.error (main.9faf9e16528f9cf98704.js:1)
    at t._error (main.9faf9e16528f9cf98704.js:1)
    at n.noMatchError (main.9faf9e16528f9cf98704.js:1)
    at t.selector (main.9faf9e16528f9cf98704.js:1)
    at t.error (main.9faf9e16528f9cf98704.js:1)
    at t._error (main.9faf9e16528f9cf98704.js:1)
    at t.error (main.9faf9e16528f9cf98704.js:1)
    at t._error (main.9faf9e16528f9cf98704.js:1)
    at t.error (main.9faf9e16528f9cf98704.js:1)
    at t._error (main.9faf9e16528f9cf98704.js:1)
    at t.error (main.9faf9e16528f9cf98704.js:1)
    at t._error (main.9faf9e16528f9cf98704.js:1)
    at j (polyfills.9f773b75ffcda6bb2a95.js:1)
    at j (polyfills.9f773b75ffcda6bb2a95.js:1)
    at polyfills.9f773b75ffcda6bb2a95.js:1
    at e.invokeTask (polyfills.9f773b75ffcda6bb2a95.js:1)
    at Object.onInvokeTask (main.9faf9e16528f9cf98704.js:1)
    at e.invokeTask (polyfills.9f773b75ffcda6bb2a95.js:1)
    at t.runTask (polyfills.9f773b75ffcda6bb2a95.js:1)
    at d (polyfills.9f773b75ffcda6bb2a95.js:1)
    at t.invokeTask (polyfills.9f773b75ffcda6bb2a95.js:1)
    at invoke (polyfills.9f773b75ffcda6bb2a95.js:1)

**Comment by lbroudoux** [comment] 2019-08-14 09:12
Oh yes! There's still this broken link. I'm closing this issue and will tackle that on another one.

**Closed by lbroudoux** 2019-08-14 09:12 UTC
Labels: kind/question

**Comment by zhushendhh** [comment] 2019-08-15 05:32
@lbroudoux 
Could I know which one is the tracking issue? Thank you.
