### ISSUE TITLE
Microcks Ui doesnt show APIs & Services

### ISSUE THREAD

**Issue by jennerEVRFLL** [microcks/microcks#528] opened 2021-12-15 09:22 UTC
Hello,

It seems I have a problem with my k8s v1.20.11 installation of microcks.  I´ve  deployed microcks on two company clusters and local minikube instance. I have tested it with different versions locally and in the cluster. The minikube instance works fine but the cluster installations have a strange behaviour.

I can create APIs:
![image](https://user-images.githubusercontent.com/91196017/146151831-b39828ea-102b-4a09-9ffa-f9fa0d5ae03b.png)
But only get a blank page when try to list them.
![image](https://user-images.githubusercontent.com/91196017/146151587-ad3e8fc7-b34e-4d0e-8fe5-cc35d36d1687.png)

The pods do not return any error messages except this warning:
<details>
<summary>Podlog</summary> 

```
08:51:54.822 [DEBUG] io.github.microcks.web.InvocationController - Getting invocations stats for last 20 days
08:51:54.822 [DEBUG] io.github.microcks.web.InvocationController - Getting top 20 invocations stats for day 20211215
08:51:54.822 [WARN] org.keycloak.adapters.RequestAuthenticator - SSL is required to authenticate. Remote address 100.x.x.34 is secure: false, SSL required for: EXTERNAL .
```

</details>

The network analysis of Chrome and Firefox shows the following errors:

![image](https://user-images.githubusercontent.com/91196017/146156003-7b6ff329-c0a2-4a7d-8098-3c51915808a1.png)

![image](https://user-images.githubusercontent.com/91196017/146156018-31797827-8792-4ab0-b221-90967da88676.png)

**Comment by jennerEVRFLL** [comment] 2021-12-15 14:43
Hi @lbroudoux 

thanks for the reply. Yes we use a external Keycloak (Keycloak Operator) and a https endpoint because we also use a apicurio instance.

Here are some information about the configuration.

<details>
<summary>Helm Values</summary> 

```
keycloak:
  install: false
  realm: apicurio
  url: apicurio.xxx.xxx.one 
  privateUrl: https://apicurio.xxx.xxx.one/auth
```
</details>

 Configured Keycloak Clients: 

![image](https://user-images.githubusercontent.com/91196017/146205344-7712e2d6-b89a-43ae-9dad-47208ee310c2.png)

Mocking feature works but also displays a blank page on mickrocks:
![image](https://user-images.githubusercontent.com/91196017/146205686-24ab1375-ce75-4185-a3c1-062aa541f8c9.png)

**Comment by lbroudoux** [comment] 2021-12-16 20:39
The #526 seems to face the same odd empty page. Maybe related?
I'm currently building a new cluster to test this out. Stay tuned

**Comment by lbroudoux** [comment] 2021-12-16 20:48
Looking at your settings, it seems that both `keycloak.url` and `keycloak.privateUrl` are pointing to the same URL. You wouldn't need `keycloak.privateUrl` though.

**Comment by lbroudoux** [comment] 2021-12-16 20:55
That said, I've tried with this setting - pointing on an external Keycloak using the same secured Ingress for both `url` and `privateUrl` and did not succeed reproducing it (yet!).

**Comment by lbroudoux** [comment] 2022-02-01 09:25
Hey @jennerEVRFLL

Any news on this one ?

**Comment by jennerEVRFLL** [comment] 2022-02-08 07:33
Hi @lbroudoux not yet. But we setting up a new Cluster right now. I'll keep you updated.

**Comment by frdrcrlt** [comment] 2022-04-04 16:27
Hi @lbroudoux, I have the same empty page when I import an API specification (OCP 4.8.27, Microcks Operator 1.5.0)

Here is the log in the my-microcks Pod application :

`16:01:48.879 [WARN] org.keycloak.adapters.RequestAuthenticator - SSL is required to authenticate. Remote address xxx.xx.xx.x is secure: false, SSL required for: EXTERNAL .`

**Comment by carolgschwend** [comment] 2022-04-08 22:18
Hi @lbroudoux, We are experiencing the same problem and getting the same error when deployed with existing keycloak instance.  

We deployed image and chart 1.2.1.  Below image shows local deployment with internal keycloak on the left vs an environment cluster with external keycloak on the right.

![image](https://user-images.githubusercontent.com/21066111/162539651-2b761fc9-c61b-44ca-807a-d47edd3ef5b1.png)

**Comment by carolgschwend** [comment] 2022-04-09 04:03
> Hi @lbroudoux, We are experiencing the same problem and getting the same error when deployed with existing keycloak instance.
> 
> We deployed image and chart 1.2.1. Below image shows local deployment with internal keycloak on the left vs an environment cluster with external keycloak on the right.
> 
> ![image](https://user-images.githubusercontent.com/21066111/162539651-2b761fc9-c61b-44ca-807a-d47edd3ef5b1.png)

I found something!  I entered part of my spec title in the 'Filter by Name...' field on the APIs & Services page and it found and listed my spec.  :)

**Comment by lbroudoux** [comment] 2022-04-12 13:11
Hey @carolgschwend 

> The hasRepositoryFilterFeatureEnabled check in ServicesPageComponent seems to prevent the service lookup unless something is entered in the filter.

This is a weird behavior as the `hasRepositoryFilterFeatureEnabled` should just condition the fetching of available services labels for filtering... Default is to fetch all services (see [default](https://github.com/microcks/microcks/blob/1.2.1/webapp/src/main/webapp/src/app/pages/services/services.page.ts#L120)) and entering a new name just call the `/api/service/search` endpoint that is also secured using Keycloak...

> `[WARN] org.keycloak.adapters.RequestAuthenticator - SSL is required to authenticate. Remote address xxx.xx.xx.x is secure: false, SSL required for: EXTERNAL .`

I assume you've got this message on the cluster that is using external Keycloak. Please make sure this endpoints is actually secured. Microcks assumed it is (just prepending `https://` to the `keycloak.url` param of your chart if you're not using a `privateUrl`) but I think the keycloak connector do extra checks that lead to above messages and bad behavior of the connector.

**Comment by lbroudoux** [comment] 2022-04-21 10:18
I'm tackling deep dive into this issue and I'm suspecting the problem is coming from the Ingress Controller / LB / Proxy that's handling the TLS termination in front of Keycloak. Keycloak provides some doc on how to correctly set up such a proxy so that it allows detection of externally handled TLS termination. Could you check https://www.keycloak.org/docs/latest/server_installation/index.html#_setting-up-a-load-balancer-or-proxy to see if your ingress controller or LB is configured accordingly?

**Comment by lbroudoux** [comment] 2022-04-21 10:18
We could eventually produce a fix for setting `ssl-required=none` but I think this is a terrible workaround ... I would say that if you need this, you can still edit the `microcks-config` ConfigMap and change the value within the application.properties entry of the ConfigMap.

**Comment by lbroudoux** [comment] 2022-04-28 12:33
Hi there!

Just added the `help wanted` label as I'm a bit out of resources on that topic ... I've tried redeploying everything - with both embedded Keycloak or external Keycloak - on a GKE cluster with standard nginx ingress controller with default settings and did not succeed reproducing this issue.

What I suspect so far is the problem should come from LB / Proxy / Ingress Controller / Network that is used to access the Keycloak instance from the Microcks pod. The Keycloak documentation proposes reference documentation on how things should be configured. See https://www.keycloak.org/docs/latest/server_installation/index.html#_setting-up-a-load-balancer-or-proxy

Every information/observation/troubleshooting hint is very welcomed on this issue! Please do contribute to help community ;-)

**Comment by mbathe19** [comment] 2022-06-14 13:43
Hello,

have the same setup like @jennerEVRFLL (we know each other).
I think the problem could be that we are both using "traefik" as ingress. I think this is the problem. 
If have time, i will redeploy the stack with nginx ingress and have a look if it is fixed. 
If yes, we have the answer.

Kind regards,

Michel

**Comment by lbroudoux** [comment] 2022-06-15 10:23
Yes please keep us updated on that issue! That would be awesome as I really struggle with this one.

**Comment by lbroudoux** [comment] 2022-06-27 19:51
Hi there! https://microcks.io/helm/index.yaml seems to be up-and-running ...

**Comment by carolgschwend** [comment] 2022-09-28 00:21
Hi @lbroudoux,

We have found our issue can be resolved if we set a few properties of the embedded microcks tomcat server.  Would you consider an update to the helm charts to give users the ability to conditionally specify additional application properties from a supplied yaml file to resolve this and potentially other scenarios they may face?  This [draft](https://github.com/microcks/microcks/pull/671/files) PR shows what worked for us.  

With this approach we can simply do a helm install and enable extraProperties and pass in the file like so:

```
 --set microcks.extraProperties.enabled=true \ 
 -f  /path-to-my-extra-properties-file/application-extra.yaml
```

The application-extra.yaml file must contain 'extraProperties' key, then any extra properties should be listed below.  For example:

```
extraProperties:
  server:
    forward-headers-strategy: native
    tomcat:
      remoteip:
        internal-proxies: .*
```

**Comment by lbroudoux** [comment] 2022-09-28 09:52
Hey @carolgschwend 
That's awesome! I was really stuck with this issue...
Don't you think it should be included by default to avoid extra configuration steps? Do you see any risk including these settings?
Also do you have an explanation on why it appears to be necessary on some installs and not some others? Is it related to specific requirements on your proxy?
Lot of questions, sorry. But very curious about it.

**Comment by aroak** [comment] 2022-09-28 13:29
Hi @lbroudoux, the settings that we typically use inside of our internal clusters don't use `.*` for internal-proxies, but a regex that matches the cluster's configured pod IP subnet. The `.*` configuration is definitely not safe as a default if the tomcat server handles any traffic that comes from the internet.

This configuration is necessary for us because due to the size and number of our clusters, we can't use only the 3 typical private IPv4 address spaces, so we have to a reserved IPv4 space such as `172.16.0.0/12`. Since those IPs aren't part of the default configuration for the internal-proxies valve, we have to provide our own regex that matches it.

For example, incoming HTTPS traffic gets handled by an appliance that terminates TLS and then routes it to the cluster as HTTP with proxy headers such as `X-Forwarded-Proto: https`. In the cluster an ingress pod with an IP of say 172.16.0.1 routes it to an application pod. With the default configuration, tomcat in that application container will ignore the `X-Forwarded..` headers because the internal-proxies regex only matches the 3 private IPv4 (and v6) blocks. However, since we configure the remoteip valve with a regex that will match 172.16.0.1, then it will treat that as an internal proxy and properly forward the proxy headers to the application code.

**Comment by carolgschwend** [comment] 2022-09-28 13:47
> Hey @carolgschwend That's awesome! I was really stuck with this issue... Don't you think it should be included by default to avoid extra configuration steps? Do you see any risk including these settings? Also do you have an explanation on why it appears to be necessary on some installs and not some others? Is it related to specific requirements on your proxy? Lot of questions, sorry. But very curious about it.
> 
> cc @frdrcrlt @jennerEVRFLL @mbathe19

Thanks @aroak and @viswatejan!

**Comment by aroak** [comment] 2022-09-28 16:38
I think that `native` is a safe default for this microcks image since it uses spring and an embedded tomcat server. Setting it to `framework` would have no benefit in this case, but it could be required if you for instance distributed microcks as a jar/war for people to deploy in some other servlet container. The `framework` option will just make Spring autoconfigure a filter to handle forwarding the proxy headers.

**Comment by lbroudoux** [comment] 2022-10-21 14:14
Now fixed and ready to use in `nightly` operator or `1.6.x` branch for Helm chart.

**Closed by lbroudoux** 2022-10-21 14:14 UTC
Labels: kind/bug, component/openshift, component/install, help wanted, component/kubernetes
