### ISSUE TITLE
Unable to update or create an importer job with a Label

### ISSUE THREAD

**Issue by leilaslimani** [microcks/microcks#642] opened 2022-08-02 00:40 UTC
Hello,

We updated our Microcks version from 1.2.0 to 1.5.2 to benefit from the RBAC feature, however we are facing behaviors that are not expected on importers.
When we create or update an importer job with a label, it is not updated on the UI, nor on the database ( screenshot below ). There is no object “labels”.
 
![image](https://user-images.githubusercontent.com/32090190/182267183-c593d2db-140c-4393-be28-fc799e03ab63.png)

I added it manually on the mongo document, and it works as expected. How can we correct this ? 
Thanks for your help & reply

**Comment by lbroudoux** [comment] 2022-08-02 12:39
Hi @leilaslimani 

Thank you for raising this one. You're totally right: seems like we have a regression on this feature. I'll have a look at it very soon.

**Comment by lbroudoux** [comment] 2022-08-02 12:55
This was an easy one but committed it to `1.6.x` branch as `1.6.0` is scheduled for a few weeks. Would you be able to integrate it by early September?

**Comment by leilaslimani** [comment] 2022-08-03 09:32
Yes definitely, we can integrate it as soon as the 1.6.0 image is ready and published on the quay registry. is there a fixed date yet ?
Thank you for your quick support

**Comment by lbroudoux** [comment] 2022-08-03 09:43
It should land for August 27th.

**Closed** 2022-08-06 15:43 UTC
Labels: component/ux, component/api, component/importer, kind/regression

**Comment by leilaslimani** [comment] 2022-09-02 14:48
Hello, 
Is there a new date planned for the arrival of 1.6.0 ?
Thank you :)

**Comment by lbroudoux** [comment] 2022-09-02 17:20
Hi @leilaslimani
We had to shift the release a bit. The plan is to release it for Sept. 10th. 🤞

**Comment by leilaslimani** [comment] 2022-09-12 09:54
Hello @lbroudoux,

We saw that the release 1.6.0 is available on the registry, so we updated today the image from 1.5.2 to 1.6.0. 
We can now create an importer job with a Label ( screenshot below ).
![image](https://user-images.githubusercontent.com/32090190/189621781-501ad99d-2ddc-482d-833b-e111579b7e9d.png)
However, the label is not added to the service  ( screenshot below ). 
![image](https://user-images.githubusercontent.com/32090190/189624558-fb6e4612-f12b-4671-93e0-9d1b55588365.png)

Is this normal ? 
Thank you :)

**Comment by lbroudoux** [comment] 2022-09-15 16:08
Hi @leilaslimani 

Job labels are not directly propagated to Services at the moment. This is because a job may potentially discover many services and also because you may want to dissociate responsibility between job management and API | Service management. 

BTW, the `1.6.0` release has now been announced there: https://twitter.com/microcksio/status/1570354986449797123
Do not hesitate to spread the word :wink:
