### ISSUE TITLE
Docker compose is broken - results in HTTP 401 - Unauthorized

### ISSUE THREAD

**Issue by saxicek** [microcks/microcks#14] opened 2018-02-07 05:45 UTC
Installed Microcks using Docker Compose. It works fine, can log in, was forced to change password. But when trying to add new job as described in http://microcks.github.io/using/index.html (Loading Samples) I get HTTP 401 Unauthorized for `POST http://localhost:8080/api/jobs`. Response header WWW-Authenticate has value `Bearer realm="microcks", error="invalid_token", error_description="Didn't find publicKey for specified kid"`. It seems like the whole `/api/jobs` endpoint is blocked because I get the same response also for `GET /api/jobs?page=0&size=20` and `GET /api/jobs/count`.

Is there anything I missed? Can I fix it somehow in KeyCloak?

**Comment by lbroudoux** [comment] 2018-02-08 14:26
Thanks for opening this issue. I was able to reproduce it using docker compose. To be fair, I always use OpenShift/Minishift so did not see that one. I'll have a further look at it. It's actually a bug.

**Comment by lbroudoux** [comment] 2018-02-08 14:55
Problem seems to come from Keycloack access defined into docker-compose. The `KEYCLOAK_URL` is used from frontend JS and thus should be addressable from browser (ie. `localhost`) and also used from backend Spring Boot to check token. However `localhost` does not lead to `keycloak`host in that case ...

Investigating...

**Comment by lbroudoux** [comment] 2018-02-22 08:36
This is now fixed by adding local configuration file that override conf into container image. Within those file, Keycloak protection is disabled, only authentication is required.

It is now easier to clone the repository to launch everything. Run:
```
git clone https://github.com/microcks/microcks.git
cd microcks/src/main/docker
docker-compose -f microcks-mongodb.yml up -d
```

**Comment by saxicek** [comment] 2018-03-20 15:33
I performed following steps:
```
docker-compose -f microcks-mongodb.yml down
git clone https://github.com/microcks/microcks.git
cd microcks/install/docker-compose
docker-compose -f microcks.yml up -d
```
Everything started but have the same issue - 401 Unauthorized for `POST http://localhost:8080/api/jobs`. I don't know much about Docker - do I need to perform any other step? Thank you!

**Comment by lbroudoux** [comment] 2018-03-20 22:14
Hi,

when using a recent version of Docker,  it's possible that your container may not be able to reach out some `localhost` address. Such address is used by Microcks for redirecting to Keycloak authentication and then checking the issued JWT token. On Mac OS, it seems that replacing the `localhost:8180` url in `microcks.yml` docker-compose file by `docker.for.mac.localhost` just work (as mentionned here https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds).

Are you using a Mac ? Does it solve your problem ?

**Comment by saxicek** [comment] 2018-03-21 06:24
No, my setup is Ubuntu virtual machine run by VMware in Windows host. :-) But I don't think Keycloak access should be the issue because after the steps above I had to login using admin/123 and was forced to change password. Also have `AUTH_SESSION_ID`, `KEYCLOAK_IDENTITY` and `KEYCLOAK_SESSION` cookies. So the Keycloak integration works somehow.

First API call failed with 401 is `GET /api/jobs?page=0&size=0` and it tries to authenticate using JWT token with payload:
```
{
  "jti": "8d482bc9-1f4e-4caf-9440-435da229c960",
  "exp": 1521613072,
  "nbf": 0,
  "iat": 1521612772,
  "iss": "http://localhost:8180/auth/realms/microcks",
  "aud": "microcks-app-js",
  "sub": "a261b664-03d1-425a-a2a7-31d0a74e8235",
  "typ": "Bearer",
  "azp": "microcks-app-js",
  "nonce": "6497f92f-cf6a-47f7-bb6f-24d22b09c2e9",
  "auth_time": 1521612767,
  "session_state": "b3b13de5-9d27-45b6-803d-175631ac2379",
  "acr": "1",
  "allowed-origins": [
    "http://localhost:8080"
  ],
  "realm_access": {
    "roles": [
      "admin"
    ]
  },
  "resource_access": {
    "realm-management": {
      "roles": [
        "view-realm",
        "view-identity-providers",
        "manage-identity-providers",
        "impersonation",
        "realm-admin",
        "create-client",
        "manage-users",
        "query-realms",
        "view-authorization",
        "query-clients",
        "query-users",
        "manage-events",
        "manage-realm",
        "view-events",
        "view-users",
        "view-clients",
        "manage-authorization",
        "manage-clients",
        "query-groups"
      ]
    },
    "account": {
      "roles": [
        "manage-account",
        "manage-account-links"
      ]
    }
  },
  "preferred_username": "admin"
}
```

But the response is again `Bearer realm="microcks", error="invalid_token", error_description="Didn't find publicKey for specified kid"`

**Comment by lbroudoux** [comment] 2018-03-21 07:37
First call is always ok because it is a redirect at the browser level. However, JWT token should then be checked when calling the `/api/jobs` endpoint. And I think this is at that time that the call to Keycloak fails. You can check that by looking at the logs of the Microcks container with `docker logs microcks -f`. You should get a low level network issue.

As I understand it, on recent versions of Docker, you should open the route for the `docker0` interface in order to get container reach `localhost` as described here: https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container

I'll try to dig that point.

**Comment by saxicek** [comment] 2018-03-21 10:37
Yes, you are probably right. I have the following in the logs:
```
[ERROR] org.keycloak.adapters.rotation.JWKPublicKeyLocator - Error when sending request to retrieve realm keys
org.keycloak.adapters.HttpClientAdapterException: IO error
Caused by: org.apache.http.conn.HttpHostConnectException: Connection to http://localhost:8180 refused
```

**Comment by lbroudoux** [comment] 2018-05-24 13:27
Adding some samples for Mac and Win docker network interfaces. Just comment/uncomment line for your system. For Linux, you'll require an extra step as described here: https://stackoverflow.com/questions/31324981/how-to-access-host-port-from-docker-container

**Closed by lbroudoux** 2018-05-24 13:27 UTC
Labels: kind/bug
