### ISSUE TITLE
Proper handling of OPTIONS (request returns 403)

### ISSUE THREAD

**Issue by denrolya** [microcks/microcks#151] opened 2019-05-30 14:40 UTC
My microcks instance is running under localhost:8080 and my tests - under localhost:4200;
My route configuration looks as follows:
```yaml
/api/login_check:
 post:
  tags: [ Auth ]
  description: Check user's credentials
  requestBody:
    description: User's credentials
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/LoginForm'
        examples:
          owner:
            $ref: '#/components/examples/OwnerCredentials'
          candidate:
            $ref: '#/components/examples/CandidateCredentials'
  responses:
    200:
      description: 'Tokens were successfully generated'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Tokens'
          examples:
            role1:
              $ref: '#/components/examples/Role1BearerAndRefreshTokens'
            role2:
              $ref: '#/components/examples/Role2BearerAndRefreshTokens'
    400:
      $ref: '#/components/responses/BadRequest'
    401:
      $ref: '#/components/responses/Unauthorized'
    404:
      $ref: '#/components/responses/NotFound'
    500:
      $ref: '#/components/responses/ServerError'
```
I've tried adding:
```yaml
options:
  description: CORS Request
  responses:
    200:
      $ref: '#/components/responses/OPTIONS-CORS-200'
```
Regardless of that, this is the result in command line, but in browser I receive error 403:
```bash
$: curl -XOPTIONS -I http://localhost:8080/rest/xxx/1.0.0/login_check
  HTTP/1.1 200
  X-Application-Context: application:prod
  Allow: GET,HEAD,POST,PUT,PATCH,DELETE,OPTIONS
  Content-Length: 0
  Date: Thu, 30 May 2019 13:05:57 GMT
```

Please help me find the way to configure it properly

**Comment by lbroudoux** [comment] 2019-06-03 11:20
Hi Den,

Thanks for opening this issue. I have some questions for you : would you please elaborate on how you actually use custom OPTIONS definitions for your API ? Including how you specify response elements for such requests ...

On the other side, we have this issue #144 about applying - by default - CORS on REST mocks so that exposed endpoints will be easily usable from mobile or browser. Would you consider this as the same use-case as yours or do you have complementary informations to setup on OPTIONS calls ?

What do you think of priotizing OPTIONS like this : the one coming from API definition if any XOR the default one with CORS headers ?

Thanks for you opinions or ideas on that topic !

**Comment by denrolya** [comment] 2019-06-03 13:59
Hello Laurent,

so, this is my options request described implicitly:

```
/route1:
  options:
    description: CORS Request
    responses:
      '200':
        $ref: '#/components/responses/OPTIONS-CORS-200'
```
Where `OPTIONS-CORS-200` looks as follows:
```
OPTIONS-CORS-200:
  description: Returned on allowed routes
  headers:
    Access-Control-Allow-Origin:
      $ref: '#/components/headers/Access-Control-Allow-Origin'
    Access-Control-Max-Age:
      $ref: '#/components/headers/Access-Control-Max-Age'
````
And headers:
```
Access-Control-Allow-Origin:
  schema:
    type: string
  example: 'Access-Control-Allow-Origin: https://localhost:4201'
Access-Control-Max-Age:
  schema:
    type: string
  example: 'Access-Control-Max-Age: 600'
```

Indeed, I think this might be the same use case. If there is any workaround for this?
I didn't really understand the question with priorities, cause I think it should be limited to API definitions, the same as one configures server & API in particular.

**Comment by lbroudoux** [comment] 2019-06-04 08:06
Thanks for clarification and full example.

Regarding priorities, it relates to #144 where I think about introducing a default handler for OPTIONS operations. It seems like many people actually did not define OPTIONS handling the explicit way into their API contract but rather rely on infrastructure or API Gateway to add basic CORS policy on their API...

**Comment by lbroudoux** [comment] 2019-06-05 07:41
Now done.

**Comment by denrolya** [comment] 2019-06-05 10:18
I'm still getting 403, after I pulled from master and rebuilt my docker containers. Am I missing something?

**Comment by lbroudoux** [comment] 2019-06-05 16:53
Hi @denrolya ,

I've used this contract attached to test on my side.
[login-options.yaml.zip](https://github.com/microcks/microcks/files/3258152/login-options.yaml.zip)

Just import it into Microcks using the Upload button. Then execute `curl -XOPTIONS http://localhost:8080/rest/Login+Options+API/1.0.0/login_check -v` to check that `OPTIONS` operation of contract is invoked.

I got this result on my laptop:
```
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> OPTIONS /rest/Login+Options+API/1.0.0/login_check HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 
< X-Application-Context: application
< Content-Type: application/json;charset=UTF-8
< Content-Length: 14
< Date: Tue, 04 Jun 2019 15:38:46 GMT
< 
* Connection #0 to host localhost left intact
{"cors": "ok"}% 
```

**Comment by denrolya** [comment] 2019-06-05 17:26
@lbroudoux  Indeed, it works with curl. I have just discovered, that I'm sending "Access-Control-Request-Method: POST" header, and this causes 403, without it I get proper 200. Do you have any ideas what could that be?

**Comment by lbroudoux** [comment] 2019-06-05 18:29
Hum ... Could you share your exact and complete API contract + your test method so that I can investigate on my side ?

**Comment by denrolya** [comment] 2019-06-06 08:15
API contract is exactly the same as yours, no difference at all, except from in your example it's /login_check - and it's /api/login_check in mine.
Here is the full list of headers that return 403 for me:
```
Host: localhost:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Referer: http://localhost:4201/login
Origin: http://localhost:4201
DNT: 1
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```, as mentioned before, without "Access-Control-Request-Method: POST" I would receive 200. And my test method is the login form of angular 6 application.

**Comment by lbroudoux** [comment] 2019-06-06 11:52
Hi Den,

I've retested with a bunch of supplemental headers and doesn't see the case when one cause returning a 403 code:

```
curl -XOPTIONS http://localhost:8080/rest/Login+Options+API/1.0.0/login_check -H "Acces-Control-Request-Method: POST" -H "Access-Control-Request-Headers: content-type" -H "User-Agent: Mozilla/5.0" -H "Origin: http://localhost:4201" -v
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> OPTIONS /rest/Login+Options+API/1.0.0/login_check HTTP/1.1
> Host: localhost:8080
> Accept: */*
> Acces-Control-Request-Method: POST
> Access-Control-Request-Headers: content-type
> User-Agent: Mozilla/5.0
> Origin: http://localhost:4201
> 
< HTTP/1.1 200 
< X-Application-Context: application
< Content-Type: application/json;charset=UTF-8
< Content-Length: 14
< Date: Thu, 06 Jun 2019 11:50:11 GMT
< 
* Connection #0 to host localhost left intact
{"cors": "ok"}% 
```

We do not intercept any of this header on the Microcks side ... maybe a matter of network setup ... You're using docker-compose deployment method right ?

**Comment by denrolya** [comment] 2019-06-06 12:07
Yes, I'm using docker-compose. Try this:
```
curl -X OPTIONS \
  'http://localhost:8080/rest/Troops+Backend+API/1.0.0/api/login_check' \
  -H 'Accept: */*' \
  -H 'Accept-Encoding: gzip, deflate' \
  -H 'Accept-Language: en-US,en;q=0.5' \
  -H 'Access-Control-Request-Headers: content-type' \
  -H 'Access-Control-Request-Method: POST' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'DNT: 1' \
  -H 'Host: localhost:8080' \
  -H 'Origin: http://localhost:4201' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:4201/login' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:67.0) Gecko/20100101 Firefox/67.0' \
  -H 'cache-control: no-cache' \
  -H 'content-length: ' \
  -H 'content-type: multipart/form-data; boundary=--------------------------055971612750266370996332'
```

**Comment by lbroudoux** [comment] 2019-06-06 12:34
Sorry, my bad, I had a typo on `Acces-Control-Request-Method` ... Once fixed, I've got same as yours. This request does not event reach the Microcks controller and is trapped before by Spring Boot framework used ...

**Comment by lbroudoux** [comment] 2019-06-06 18:22
Seems like the problem is not coming from `Access-Control-Request-Method` but from the usage of this one next to `Origin`. Once you remove the `Origin` header, the request is accepted by the Spring Boot web framework layers and then transferred to Microcks controller ...

@nmasse-itix Would you have some time reviewing that and giving us your HTTP expert point of view? 😃

**Comment by denrolya** [comment] 2019-06-16 13:06
Hey guys. Is there any update on this?

**Comment by lbroudoux** [comment] 2019-11-07 17:23
Reopening following investigations done through #172

**Comment by lbroudoux** [comment] 2019-11-13 19:46
Now ok with `Allow Origin: *` setup when CORS is globally enabled using `application.properties` file and setting `mocks.rest.enable-cors-policy` to `true`.

**Closed by lbroudoux** 2019-11-13 19:46 UTC
Labels: component/mocks, kind/bug
