### ISSUE TITLE
Services are still active and available even after jobs are removed

### ISSUE THREAD

**Issue by aniketvsawant** [microcks/microcks#74] opened 2018-11-20 17:36 UTC
Hi Team,

Whats the best way to clean up the services in microcks ? I can see the services are active and available even after stopping and removing the jobs. Is it the expected behavior of the tool ? The way right now i am doing is scaling down the openshift pod to 0 and scale up again to 1. Please let me know.

Thanks.

**Comment by lbroudoux** [comment] 2018-11-20 18:05
Hi,

Yes this is expected behavior as you may want to stop refreshing service definitions because service is deprecated or no more evolving but you may want to keep existing version and samples in Microcks. 

You can delete a Service when logged as an administrator. Delete action appears on a service row. 

In order to become administrator, you have to go to Keycloak console within the Microcks realm and add the import admin role to a user in the User Management. I plan to add the ability to do this from Microcks UI in a near future. 

Cheers,

**Comment by lbroudoux** [comment] 2018-11-27 14:19
Closing cause no remarks

**Closed by lbroudoux** 2018-11-27 14:19 UTC
Labels: kind/question
