### ISSUE TITLE
UI hangs when loading / rendering large payload dataset

### ISSUE THREAD

**Issue by ghost** [microcks/microcks#979] opened 2023-11-03 12:14 UTC
### Describe the bug

When you have a request with a lot of responses the UI frezzes upon opening large data.

### Expected behavior

The UI should not freeze but show a loading icon or somthing

### Actual behavior

The UI freezes and becomes unusable

### How to Reproduce?

1. load this yaml file 
https://file.io/pQ4qP3zQLNhN

2. go to the service and open the operation. The UI will freeze for 4~sec. Of cause adding examples or making them bigger worsen the problem.

### Microcks version or git rev

1.8.x

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

**Comment by lbroudoux** [comment] 2023-11-13 15:33
Thanks for opening this one. I tried to reproduce with your provided file and see a 3 or 4-second freeze when expanding the operation details. After some research, this looks like the highlighting library we're using (https://github.com/murhafsousli/ngx-highlightjs) is the one causing this freeze on JSON response rendering. Will look if some configuration options may help make things faster.

**Comment by lbroudoux** [comment] 2023-11-13 15:37
Note: `ngx-hightlightjs` is using https://highlightjs.org/ under the hood and we're resolving version `10.0.3` of this core lib

**Comment by lbroudoux** [comment] 2023-11-13 15:49
Adding the `[languages]="['json', 'xml', 'yaml']"` make the things way better!

**Comment by lbroudoux** [comment] 2023-11-13 15:54
Hey @apoorva256,

I measured than forcing the languages detection to the subset of the one commonly used, helps reducing the rendering time. The "freeze" effect I see now is only ~0.5 sec. Can you check and confirm it also helps on your side?

**Comment by apoorva256** [comment] 2023-11-17 10:12
Sorry for the late answer. 
The UI definetly feels better but is still slow. I will look into the code and see if i can do smth

**Comment by apoorva256** [comment] 2023-11-17 10:53
@lbroudoux How do you start the angular dev env.
I am currenltly having problems with the dependencies.
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: microcks-ui@1.0.0
npm ERR! Found: @angular/common@8.2.14
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~8.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"<8.0.0" from patternfly-ng@4.5.2
npm ERR! node_modules/patternfly-ng
npm ERR!   patternfly-ng@"^4.5.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/apoorva/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/apoorva/.npm/_logs/2023-11-17T10_50_34_350Z-debug-0.log
```

**Comment by lbroudoux** [comment] 2023-11-17 11:23
I start the Angular dev server with simply `ng serve` commands. If you're on Mac, resolving npm dependencies can be difficult sometimes and I may use `npm install --force` to get the correct ones.

**Comment by apoorva256** [comment] 2023-11-17 12:19
> I start the Angular dev server with simply `ng serve` commands. If you're on Mac, resolving npm dependencies can be difficult sometimes and I may use `npm install --force` to get the correct ones.

Thanks, works with `npm install --force`

**Closed** 2024-01-03 16:10 UTC
Labels: component/ux, kind/enhancement
