### ISSUE TITLE
Examples in splitted files are not loaded as samples

### ISSUE THREAD

**Issue by Selveris** [microcks/microcks#1195] opened 2024-06-10 14:33 UTC
### Describe the bug

I wrote an AsyncAPI document in multiples files, the main file with general information then channels and schemas in separate files.
The examples for the messages, located in the channels files, are not loaded correctly as samples.

If the channels with messages and examples are put in the main file it works correctly

PS: the same issue seems to happen with openAPI document

### Expected behavior

Messages examples should be correctly identified and loaded as sample even when defined in a separate file

### Actual behavior

Messages examples are not loaded

### How to Reproduce?

gist project: https://gist.github.com/Selveris/562dbde3d41f8ea2c9a04b595951cca5

- Import the project in Microcks and check the (non existing) samples for the testOperation

![image](https://github.com/microcks/microcks/assets/89778787/ce5db54f-31ca-4e9c-82ab-8c4c016eaed5)

### Microcks version or git rev

1.9.1

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

helm chart

### Additional information

The import of the API has been done through scheduled import

**Comment by lbroudoux** [comment] 2024-06-10 14:36
Hello,
Can you explain how you're importing it in Microcks? Via upload or scheduled import? It is supposed to work only for scheduled import.

**Comment by Selveris** [comment] 2024-06-11 07:40
> Hello, Can you explain how you're importing it in Microcks? Via upload or scheduled import? It is supposed to work only for scheduled import.

I did it via the scheduled import

**Comment by lbroudoux** [comment] 2024-06-11 09:21
Ok. Will have a look at it.

In the meantime, can you try creating a new scheduled import using this URL: https://gitlab.com/api/v4/projects/53583367/repository/files/complex-example-2%2Fopenapi.yaml/raw?head=main ? 

This is the public repo we're using for testing the import of complex splitted OpenAPI files (it is accessible via https://gitlab.com/lbroudoux/microcks-tests/-/tree/main/complex-example-2?ref_type=heads)

**Comment by lbroudoux** [comment] 2024-06-11 09:51
Oh oh... I got it...
In fact, the issue is due to the way you reference messages in your operation.

Currently, you're using:
```yaml
operations:
  testOperation:
    [...]
    messages:
      - $ref: '#/channels/tests/messages/testMessage'
```
That leads to a missing node, as Microcks doesn't detect that we have nested references. It tries to resolve the `#/channels/tests/messages/testMessage` in the current document but can't find it.

If you change the declaration to:
```yaml
operations:
  testOperation:
    [...]
    messages:
      - $ref: './channels-split.yaml#/tests/messages/testMessage'
```
this actually works!

I'm going to do some research to see if nested `$ref` is a must-a-have support or if we should stick with direct file reference. I'll let you know.

**Comment by Selveris** [comment] 2024-06-11 11:45
Great, thanks for finding the fix.

I think that supporting nested ref would be nice as it how the `asyncapi validate` tool work, and it also requires to import the correct file only once in channel
But that's mainly personal taste

Anyway thanks for this quick support and keep the good work!

**Comment by lbroudoux** [comment] 2024-06-11 12:15
I'm currently discussing with some guys at JSON Schema and AsyncAPI whether it's a valid approach.

It looks like the canonical standard for JSON Reference and JSON Pointers does not include "seeing through" nested references: a JSON Pointer should be valid considering the current document root. That doesn't mean that some tools are not implementing this nesting but it seems that standard prevents it... I will keep this one opened since I get a comprehensive vision on this.

**Comment by lbroudoux** [comment] 2024-06-19 15:02
Got confirmation for JSON spec leads. Microcks behaviour is correct even if AsyncAPI tooling goes beyond. Closing this issue.

**Closed by lbroudoux** 2024-06-19 15:02 UTC
Labels: kind/bug, status/wontfix, component/mocks, component/importer
