### ISSUE TITLE
[gRPC] Mocks with requests containing fields with type Any fail to respond

### ISSUE THREAD

**Issue by camaral** [microcks/microcks#1265] opened 2024-08-12 23:56 UTC
### Describe the bug

[GrpcServerCallHandler.java](https://github.com/microcks/microcks/blob/master/webapp/src/main/java/io/github/microcks/web/GrpcServerCallHandler.java#L191) tries to print the gRPC request as a json, but it does not consider that the request could contain a field with type "Any". 

In order to print Any in json, one needs to provide a TypeRegistry including the descriptor of all types that may be included in the Any field, [here is](https://github.com/protocolbuffers/protobuf/blob/v27.3/java/util/src/test/java/com/google/protobuf/util/JsonFormatTest.java#L1001) a test class from protocol buffers showing examples.

### Expected behavior

gRPC requests containing the type Any should respond normally.

### Actual behavior

Microcks returns the following error.
```
ERROR:
  Code: Unknown
  Message: Unexpected throwable during GRPC input request processing
``` 

and logs the following messages.
```
23:46:43.555  INFO 1 --- [executor-3] i.g.m.web.GrpcServerCallHandler          : Servicing mock response for service [example.v1.ExampleServiceV1, example.v1] and method Example
2024-08-12T23:46:43.587179750Z 23:46:43.585 ERROR 1 --- [executor-3] i.g.m.web.GrpcServerCallHandler          : Unexpected throwable during GRPC input request processing
2024-08-12T23:46:43.587268541Z 
2024-08-12T23:46:43.587273875Z com.google.protobuf.InvalidProtocolBufferException: Cannot find type for url: type.googleapis.com/example.v1.ExampleParametersV1
2024-08-12T23:46:43.587275625Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.printAny(JsonFormat.java:857)
2024-08-12T23:46:43.587277625Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.access$1000(JsonFormat.java:685)
2024-08-12T23:46:43.587343541Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl$1.print(JsonFormat.java:758)
2024-08-12T23:46:43.587346291Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:737)
2024-08-12T23:46:43.587347291Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1242)
2024-08-12T23:46:43.587348583Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1107)
2024-08-12T23:46:43.587349666Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1032)
2024-08-12T23:46:43.587350791Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1010)
2024-08-12T23:46:43.587352125Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:740)
2024-08-12T23:46:43.587353208Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1242)
2024-08-12T23:46:43.587354291Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1107)
2024-08-12T23:46:43.587355541Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1032)
2024-08-12T23:46:43.587356541Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1010)
2024-08-12T23:46:43.587358250Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:740)
2024-08-12T23:46:43.587360500Z 	at com.google.protobuf.util.JsonFormat$Printer.appendTo(JsonFormat.java:344)
2024-08-12T23:46:43.587363375Z 	at com.google.protobuf.util.JsonFormat$Printer.print(JsonFormat.java:354)
2024-08-12T23:46:43.587365000Z 	at io.github.microcks.web.GrpcServerCallHandler$MockedUnaryMethod.invoke(GrpcServerCallHandler.java:178)
2024-08-12T23:46:43.587366375Z 	at io.github.microcks.web.GrpcServerCallHandler$MockedUnaryMethod.invoke(GrpcServerCallHandler.java:100)
2024-08-12T23:46:43.587368833Z 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
2024-08-12T23:46:43.587372916Z 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
2024-08-12T23:46:43.587377750Z 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861)
2024-08-12T23:46:43.587382875Z 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
2024-08-12T23:46:43.587387208Z 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
2024-08-12T23:46:43.587388750Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-08-12T23:46:43.587390000Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-08-12T23:46:43.587391750Z 	at java.base/java.lang.Thread.run(Thread.java:840)
```

#### **`example_service.proto`**
```
syntax = "proto3";
package example.v1;

import "google/protobuf/any.proto";

service ExampleServiceV1 {
  rpc Example (ExampleMessage) returns (ExampleResponseMessage) {}
}

message ExampleMessage {
  message ExamplePayload {
    google.protobuf.Any parameters = 1;
  }
  ExamplePayload payload = 1;
}

message ExampleResponseMessage {
  message ExampleResponsePayload {
  }
  ExampleResponsePayload payload = 1;
}
```

#### **`example_type.proto`**
```
syntax = "proto3";
package example.v1;

message ExampleParametersV1 {
  string text = 1;
}
```

#### **`example-service.proto.ExampleServiceV1.postman_collection.json`**
```
{
    "info": {
        "_postman_id": "b0d3e98b-60a6-4f73-9050-1a7996efedf5",
        "name": "example.v1.ExampleServiceV1",
        "description": "version=example.v1 - This collection is an example",
        "schema": "https://schema.getpostman.com/json/collection/v2.0.0/collection.json",
        "_exporter_id": "26713960"
    },
    "item": [
        {
            "name": "Example",
            "item": [
                {
                    "name": "Example",
                    "request": {
                        "method": "POST",
                        "header": [],
                        "url": {
                            "raw": "http:///Example",
                            "protocol": "http",
                            "path": [
                                "Example"
                            ]
                        }
                    },
                    "response": [
                        {
                            "name": "Example response",
                            "originalRequest": {
                                "method": "POST",
                                "header": [
                                    {
                                        "key": "Content-Type",
                                        "name": "Content-Type",
                                        "value": "application/json",
                                        "type": "text"
                                    }
                                ],
                                "body": {
                                    "mode": "raw",
                                    "raw": "{}",
                                    "options": {
                                        "raw": {
                                            "language": "json"
                                        }
                                    }
                                },
                                "url": {
                                    "raw": "http:///Example",
                                    "protocol": "http",
                                    "path": [
                                        "Example"
                                    ]
                                }
                            },
                            "_postman_previewlanguage": "json",
                            "header": [],
                            "cookie": [],
                            "body": "{}"
                        }
                    ]
                }
            ]
        }
    ]
}
```

Import mocks

```shell
microcks-cli import './example_service.proto:true,./example-service.proto.ExampleServiceV1.postman_collection.json:false' --microcksURL=http://grpc-mocks:8080/api --insecure --keycloakClientId=foo --keycloakClientSecret=bar
```

Request
```shell
grpcurl --plaintext \
  --import-path ./ \
  --proto ./example_type.proto \
  --proto ./example_service.proto \
  -d '{
  "payload": {
    "parameters": {
      "@type": "type.googleapis.com/example.v1.ExampleParametersV1",
      "text": "an example"
    }
  }
}' localhost:9201 example.v1.ExampleServiceV1/Example
```

### Microcks version or git rev

quay.io/microcks/microcks-uber:1.9.1

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

**Comment by lbroudoux** [comment] 2024-08-14 08:44
Hey @camaral,

Thanks a lot for this detailed report! I was not aware of these details of `JsonFormat`. I succeeded in reproducing and I think I got a fix. I'm looking for the best way to implement this. I'll let you know as soon as the fix is available in the `nightly` container image.

Cheers,

**Comment by lbroudoux** [comment] 2024-08-14 08:45
BTW have you seen that you can now use [APIExamples](https://microcks.io/documentation/references/examples/) instead of Postman Collection for specifying your GRPC samples?

**Comment by lbroudoux** [comment] 2024-08-14 11:54
The fix is not included in `quay.io/microcks/microcks-uber:nightly`.  Can you test it and give feedback?

**Comment by camaral** [comment] 2024-08-14 15:18
Hey @lbroudoux, thank you for the very quick response. 
I didn't know about APIExamples, and I think this is a way better way to describe the gRPC requests. Thank you for sharing!

About the fix, I saw you've added the message that goes inside the Any in the same file [[here](https://github.com/microcks/microcks/commit/a00dbdf4c64f025be4fc36ff4a6c156a72eea3c7#diff-7548cac426347cfaf12423554344d68ef6626fa68838b152a576b6cf2489cb71)]. This is unfortunately not my use case, and I will give you more details, and hopefully it will be clearer. 

I have a kind of gateway service that accepts requests that are implemented by multiple services. So the gateway provides an API that groups all protos, but the services have only the proto that they implement. Using the example I already gave, it would look something like the following.

#### **`gateway_example_service.proto`**
```
syntax = "proto3";
package example.v1;

import "example_type.proto";
import "another_example_type.proto";

service ExampleServiceV1 {
  rpc Example (ExampleMessage) returns (ExampleResponseMessage) {}
}

message ExampleMessage {
  message ExamplePayload {
    oneof parameters {
         ExampleParametersV1 example = 1;
         AnotherExampleParametersV1 anotherExample = 2;
     }
  }
  ExamplePayload payload = 1;
}
```

As you can see, the gateway is strongly typed. But when it calls the actual service, it forwards the parameters packed in a field of type Any. So `example_service.proto` is the definition used by both `example` and `anotherExample` services, but `example` service implementation uses `example_type.proto`, and `anotherExample` uses `another_example_type.proto`. But only the gateway sees both message types. 

I am using microcks to test my implementation of the gateway, that is, microcks is simulating the actual services.

**Comment by lbroudoux** [comment] 2024-08-14 15:34
I've done this for simplicity of usage within the unit test. However it should work the same way if splitted into different proto files as I am using all the FileDescriptorSet available types to feed the registry. 

I'll will try another live test on tomorrow.

**Comment by camaral** [comment] 2024-08-14 16:41
I've tested  with my use case, and the example that I've provided in this issue. Both still fail. Just to reinforce, here's the request and the new stack trace. Notice GrpcServerCallHandler.java:**194** as evidence that I am using your nightly version.

```shell
grpcurl --plaintext \
  --import-path ./ \
  --proto ./example_type.proto \
  --proto ./example_service.proto \
  -d '{
  "payload": {
    "parameters": {
      "@type": "type.googleapis.com/example.v1.ExampleParametersV1",
      "text": "some text"
    }
  }
}' localhost:9201 example.v1.ExampleServiceV1/Example
```

```
2024-08-14T16:37:47.571555300Z 16:37:47.571  INFO 1 --- [executor-0] i.g.m.web.GrpcServerCallHandler          : Servicing mock response for service [example.v1.ExampleServiceV1, example.v1] and method Example
2024-08-14T16:37:47.579177758Z 16:37:47.578 ERROR 1 --- [executor-0] i.g.m.web.GrpcServerCallHandler          : Unexpected throwable during GRPC input request processing
2024-08-14T16:37:47.579218841Z 
2024-08-14T16:37:47.579223925Z com.google.protobuf.InvalidProtocolBufferException: Cannot find type for url: type.googleapis.com/example.v1.ExampleParametersV1
2024-08-14T16:37:47.579225466Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.printAny(JsonFormat.java:857)
2024-08-14T16:37:47.579227133Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.access$1000(JsonFormat.java:685)
2024-08-14T16:37:47.579228300Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl$1.print(JsonFormat.java:758)
2024-08-14T16:37:47.579229466Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:737)
2024-08-14T16:37:47.579230675Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1242)
2024-08-14T16:37:47.579231925Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1107)
2024-08-14T16:37:47.579233050Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1032)
2024-08-14T16:37:47.579234175Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1010)
2024-08-14T16:37:47.579235300Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:740)
2024-08-14T16:37:47.579236508Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1242)
2024-08-14T16:37:47.579237591Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.printSingleFieldValue(JsonFormat.java:1107)
2024-08-14T16:37:47.579238716Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.printField(JsonFormat.java:1032)
2024-08-14T16:37:47.579239800Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:1010)
2024-08-14T16:37:47.579240883Z 	at com.google.protobuf.util.JsonFormat$PrinterImpl.print(JsonFormat.java:740)
2024-08-14T16:37:47.579244258Z 	at com.google.protobuf.util.JsonFormat$Printer.appendTo(JsonFormat.java:344)
2024-08-14T16:37:47.579246716Z 	at com.google.protobuf.util.JsonFormat$Printer.print(JsonFormat.java:354)
2024-08-14T16:37:47.579266216Z 	at io.github.microcks.web.GrpcServerCallHandler$MockedUnaryMethod.invoke(GrpcServerCallHandler.java:194)
2024-08-14T16:37:47.579268508Z 	at io.github.microcks.web.GrpcServerCallHandler$MockedUnaryMethod.invoke(GrpcServerCallHandler.java:115)
2024-08-14T16:37:47.579269800Z 	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182)
2024-08-14T16:37:47.579271008Z 	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:351)
2024-08-14T16:37:47.579273258Z 	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:861)
2024-08-14T16:37:47.579274216Z 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
2024-08-14T16:37:47.579275091Z 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
2024-08-14T16:37:47.579276008Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-08-14T16:37:47.579276883Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-08-14T16:37:47.579277841Z 	at java.base/java.lang.Thread.run(Thread.java:840)
2024-08-14T16:37:47.579278716Z 

```

**Comment by lbroudoux** [comment] 2024-08-20 12:24
I've made another test, and I think the result you get is related to how you load the `proto` file(s) in Microcks.

In the [`example-any-v1.proto`](https://github.com/microcks/microcks/blob/1.10.x/webapp/src/test/resources/io/github/microcks/util/grpc/example-any-v1.proto) mentioned above, all the messages types have been put in the same proto file so Microcks find them all. Good.

Your concern was about splitting them into 2 files: `example_service.proto` and `example_type.proto` as mentioned above. 

With the import process you're using above (`microcks-cli import './example_service.proto:true,./example-service.proto.ExampleServiceV1.postman_collection.json:false'`) is actually unaware of `example_type.proto` to load it and register the `ExampleParametersV1` into the type registry...

To load dependencies into Microcks, you'll first have to add an explicit import it into the proto file and change `example_service.proto` to:

```proto
syntax = "proto3";
package example.v1;

import "google/protobuf/any.proto";
import "example_type.proto";

service ExampleServiceV1 {
  rpc Example (ExampleMessage) returns (ExampleResponseMessage) {}
}

message ExampleMessage {
  message ExamplePayload {
    google.protobuf.Any parameters = 1;
  }
  ExamplePayload payload = 1;
}

message ExampleResponseMessage {
  message ExampleResponsePayload {
  }
  ExampleResponsePayload payload = 1;
}
```

Now you need to import this in Microcks using an [Importer](https://microcks.io/documentation/guides/usage/importing-content/#2-import-content-via-importer). This implies putting both files in a Git repository or a local http server (sometime I just use `python3 -m http.server` locally) and asking Microcks to pull them. This way Microcks as a base URL to resolve dependencies against.

Using this method, you'll see the logs in Microcks are a bit different:

```
14:00:10.069  INFO 99824 --- [heduling-1] i.github.microcks.service.JobService     : Starting import for job 'Proto with Any local'
14:00:10.070  INFO 99824 --- [heduling-1] i.g.microcks.service.ServiceService      : Importing service definitions from http://localhost:8000/example_service.proto
14:00:10.073  INFO 99824 --- [heduling-1] i.g.m.u.MockRepositoryImporterFactory    : Found a syntax = proto3 pragma in file so assuming it's a GRPC Protobuf spec to import
14:00:10.073  INFO 99824 --- [heduling-1] i.g.microcks.util.ReferenceResolver      : Downloading a reference file at http://localhost:8000/example_type.proto
protoc-jar: protoc version: 3.21.8, detected platform: osx-aarch_64 (mac os x/aarch64)
protoc-jar: cached: /var/folders/n9/_hd3r9c13sz76379nr9lg3p40000gn/T/protocjar.webcache/com/google/protobuf/protoc/maven-metadata.xml
protoc-jar: cached: /var/folders/n9/_hd3r9c13sz76379nr9lg3p40000gn/T/protocjar.webcache/com/google/protobuf/protoc/3.21.8/protoc-3.21.8-osx-aarch_64.exe
protoc-jar: executing: [/var/folders/n9/_hd3r9c13sz76379nr9lg3p40000gn/T/protocjar2559027172192106977/bin/protoc.exe, -I/var/folders/n9/_hd3r9c13sz76379nr9lg3p40000gn/T/protocjar2559027172192106977/include, --include_imports, --proto_path=/var/folders/n9/_hd3r9c13sz76379nr9lg3p40000gn/T, --descriptor_set_out=/var/folders/n9/_hd3r9c13sz76379nr9lg3p40000gn/T/microcks-17241552100703042077867151537156.download.pbb, microcks-17241552100703042077867151537156.download]
microcks-17241552100703042077867151537156.download:5:1: warning: Import example_type.proto is unused.
14:00:10.256  INFO 99824 --- [heduling-1] i.g.microcks.service.ServiceService      : Having imported 1 services definitions into repository
14:00:10.258  INFO 99824 --- [heduling-1] i.github.microcks.service.JobService     : Import of job 'Proto with Any local' done
```

Even if it says: `Import example_type.proto is unused`, the type definitions it contains will actually be available now at runtime for any type serialization/deserialization.

Testing it:

```sh
$ grpcurl --plaintext \
-d '{
  "payload": {
    "parameters": {
      "@type": "type.googleapis.com/example.v1.ExampleParametersV1",
      "text": "an example"
    }
  }
}' localhost:9090 example.v1.ExampleServiceV1/Example
=== OUTPUT ===
{}
```

So I think serialization of Any is now correctly implemented but the restrictions we have are due to the way proto are loaded into Microcks. I have not yet tested [your trick](https://github.com/microcks/microcks/issues/449#issuecomment-2140854447) of putting the dependent proto in `/tmp` but will try to have a try.

**Comment by camaral** [comment] 2024-08-20 15:40
Is there an automated way to tell microcks-uber where the artifact repository is? I mean, without having to go through the UI and setting up the Importer. An env-var would be nice, then I could do something like:

#### **`docker-compose.yaml`**
```
services:
  grpc-protos-server:
    image: python:3.12.4-alpine3.20
    volumes:
      - ./build/extracted-include-protos/main:/public
    ports:
      - "8000:8000"
    working_dir: /public
    command:
      - python
      - -m
      - http.server

  grpc-mocks:
    image: quay.io/microcks/microcks-uber:nightly
    ports:
      - '9081:8080'
      - '9201:9090'
    environment:
      - ARTIFACT_REPOSITORY_URL=http://localhost:8000 # <= THIS IS WHAT I AM LOOKING FOR
```

This would be way better than the workaround with the `/tmp` folder.

**Comment by camaral** [comment] 2024-08-20 23:01
Hey @lbroudoux,

Since I cannot add the `import` declaration in my original proto definitions, I have added a third file in my application's test resources, which imports the other two protos.

`example_service_implementation.proto`
```
syntax = "proto3";
package example.v1;

import "example_service.proto";
import "example_type.proto";
```

I have tested it with `quay.io/microcks/microcks-uber:nightly` and `quay.io/microcks/microcks-cli:0.5.5`, and it is working.

**Comment by lbroudoux** [comment] 2024-08-26 17:18
Hey @camaral 

> Is there an automated way to tell microcks-uber where the artifact repository is? I mean, without having to go through the UI and setting up the Importer. An env-var would be nice, then I could do something like:

I like this idea! We could have a default `DEPENDENCY_REPOSITORY_URL` that applies as a default for uploaded artifacts. Also, this could be a broader definition thatn an HTTP URL, allowing values with `file://` and that will resolve dependencies within a mounted directory (this will prevent running an extra Http server).

Would you like to open another issue describing this? I think we can close this one as the $subject has now been sorted out.

What do you think?

**Closed** 2024-08-26 17:27 UTC
Labels: kind/bug, component/mocks

**Comment by camaral** [comment] 2024-08-28 22:58
@lbroudoux, would you release a final version of the microcks-uber image with this fix, please? That's just I don't need to use the `nightly`
